"use strict";
var studentRollNo = [1, 2, 3, 4, 5];
console.log(studentRollNo[2]);
var sum = studentRollNo[2] + studentRollNo[1];
console.log(sum);
studentRollNo[0] = 0;
var sum2 = studentRollNo[0] + studentRollNo[1];
console.log(sum2);
var studentName = ["Ali", "Zain", "Raheeq", "Zair"];
console.log(studentName[3]);
studentName[3] = "Ahmad";
console.log(studentName[3]);
